import { writeFile } from "node:fs/promises";
import path from "node:path";
import type { CaptureResult, AssembleResult } from "../types/index.js";
import { writeRunMode } from "./writeRunMode.js";
import { writeServingConfig } from "./servingConfig.js";
import { detectDomainLockedCredentials } from "./credentialWarnings.js";

/**
 * Writes the `.study-clone` provenance marker required by the PRD
 * (section 9: "Provenance marking"). This file's presence is the
 * project's own self-identification mechanism — any output directory
 * produced by this tool should be unambiguously identifiable as such,
 * independent of whether the user has also read the README.
 */
async function writeProvenanceMarker(
  outputDir: string,
  capture: CaptureResult
): Promise<void> {
  const marker = {
    tool: "frontend-study-cloner",
    mode: "run",
    sourceUrl: capture.targetUrl,
    capturedAt: capture.capturedAt,
    notice:
      "This directory was generated by an automated capture tool for personal " +
      "learning and study purposes. It is not the original source code, and " +
      "must not be redistributed, rehosted, or used commercially.",
  };
  await writeFile(
    path.join(outputDir, ".study-clone"),
    JSON.stringify(marker, null, 2),
    "utf-8"
  );
}

export interface AssembleRunModeResult extends AssembleResult {
  credentialWarnings: ReturnType<typeof detectDomainLockedCredentials>;
}

/**
 * The single entrypoint for turning a completed capture into a working
 * Run-mode output directory. This is what the CLI calls after
 * `captureSite()` finishes; Study mode (beautification, component
 * inference) is a separate, later pass that consumes this same
 * CaptureResult independently — see PRD section 5's design principle
 * that Run mode must work without Study mode ever executing.
 */
export async function assembleRunMode(
  capture: CaptureResult,
  outputDir: string
): Promise<AssembleRunModeResult> {
  const writeResult = await writeRunMode(capture, { outputDir });
  const servingFiles = await writeServingConfig(outputDir, capture);
  await writeProvenanceMarker(outputDir, capture);

  const credentialWarnings = detectDomainLockedCredentials(capture.assets);

  const warnings = [...writeResult.warnings];
  if (capture.externalDependencies.length > 0) {
    warnings.push(
      `This site's captured code still references ${capture.externalDependencies.length} ` +
        `external domain(s) that will remain live dependencies: ${capture.externalDependencies.join(", ")}. ` +
        `Features relying on these will only work if those services remain reachable and ` +
        `permit requests from this output's serving origin.`
    );
  }
  for (const cred of credentialWarnings) {
    warnings.push(`[${cred.service}] ${cred.description} (found in ${cred.bundleUrl})`);
  }

  return {
    outputDir,
    filesWritten: [...writeResult.filesWritten, ...servingFiles, ".study-clone"],
    warnings,
    credentialWarnings,
  };
}
